Update database_cleaner to the latest version
Was previously getting the following error:

An error occurred in a `before(:suite)` hook.
Failure/Error: DatabaseCleaner.clean_with(:truncation)

NoMethodError:
  undefined method `schema_migration' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x0000000000dc00 env_name="test" role=:writing>
# ./spec/rails_helper.rb:64:in `block (2 levels) in <top (required)>'