Default radius if radius parameter can not be parsed
Users bookmarked bad formatted URLs from the old live site.

With the prefiltering this won't happen anymore but if the user
bookmarked their searches we need to make sure we don't break
the prefiltering results.

Error: https://dfe-teacher-services.sentry.io/issues/6086894349/?alert_rule_id=11137790&alert_type=issue&notification_uuid=41008102-811c-497d-ac13-3a0aa832c51b&project=1377944&referrer=slack

What happened?
A Sentry error is getting raised quite frequently.
This could be causeing disruption to users on Find.

What was supposed to happen?
User makes request to search courses and does not encounter an error