[1160] Fix how Faraday is used
Without this fix, Faraday throws an exception:

NoMethodError: undefined method `bytesize' for {:email=>"xxxx"}:Hash

According to https://github.com/lostisland/faraday/issues/726, we should be calling
a `to_json` on the body.