[2126] mcb - fix rolling over already-rolled over providers
Previous output:

> /home/tim/repo/dfe/manage/backend/app/services/sites/copy_to_provider_service.rb:4:
> in `execute': undefined method `sites' for nil:NilClass (NoMethodError)

This was because `new_provider` was `nil` if the rollover copy of the
provider already existed.